name: Monitor SonarQube Alerts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  monitor-alerts:
    uses: join-com/shared-workflows/.github/workflows/sonarqube-monitor-alerts.yml@master
    secrets: inherit