name: SonarQube Master

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  execute:
    uses: join-com/shared-workflows/.github/workflows/sonarqube-master.yml@master
    secrets: inherit
    with:
      skip-coverage: true
