name: Monitor License Compliance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  monitor-alerts:
    uses: join-com/shared-workflows/.github/workflows/trivy-license-monitor-compliance.yml@master
    secrets: inherit